# Generated by Django 5.1.4 on 2025-01-03 00:52

import django.db.models.deletion
import pendulum
import util.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("util", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", util.fields.DateTimeField(default=pendulum.now)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            (
                                "Politician survey completed",
                                "Polium Politician Survey Completed",
                            ),
                            (
                                "Registered to vote in this race",
                                "Polium Registered To Vote",
                            ),
                            (
                                "Volunteered with the candidate 1 hour",
                                "Polium Volunteered With Candidate 1H",
                            ),
                            ("Voted in an election", "Polium Voted In Election"),
                        ],
                        max_length=50,
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                ("url", models.CharField(max_length=250)),
                ("entity", models.IntegerField()),
                ("last_updated_at", util.fields.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
