# Generated by Django 5.1.4 on 2025-01-04 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polium", "0002_candidatesurvey"),
        ("util", "0002_activity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Race",
            new_name="Election",
        ),
        migrations.RenameModel(
            old_name="CandidateSurvey",
            new_name="PoliticianSurvey",
        ),
        migrations.RenameField(
            model_name="candidate",
            old_name="race",
            new_name="election",
        ),
        migrations.AlterField(
            model_name="politiciansurvey",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="polium.politician"
            ),
        ),
    ]
