# Generated by Django 5.1.4 on 2025-01-06 02:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polium", "0003_rename_race_election_and_more"),
        ("util", "0002_activity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PoliticianSurvey",
            new_name="CandidateSurvey",
        ),
    ]
