# Generated by Django 5.1.4 on 2025-01-06 02:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polium", "0005_alter_candidatesurvey_unique_together"),
        ("util", "0002_activity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CandidateSurvey",
            new_name="PoliticianSurvey",
        ),
    ]
