# Generated by Django 5.1.4 on 2025-01-11 16:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polium", "0006_rename_candidatesurvey_politiciansurvey"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="politiciansurvey",
            old_name="entity",
            new_name="politician",
        ),
        migrations.AlterUniqueTogether(
            name="politiciansurvey",
            unique_together={("politician", "user")},
        ),
    ]
