# Generated by Django 5.1.4 on 2025-01-12 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polium", "0007_rename_entity_politiciansurvey_politician_and_more"),
        ("util", "0002_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="politiciansurvey",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="util.activity",
            ),
        ),
    ]
