# Generated by Django 5.1.4 on 2025-01-12 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polium", "0008_alter_politiciansurvey_activity"),
        ("util", "0002_activity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="politician",
            name="rating",
        ),
        migrations.AddField(
            model_name="candidate",
            name="rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="election",
            name="categories",
            field=models.ManyToManyField(to="util.category"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="politician",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidacies",
                to="polium.politician",
            ),
        ),
    ]
